name: Hello GitHub Actions

on:
  workflow_dispatch: {}
  # (si ya tienes otros triggers, se pueden dejar)
  # push:
  #   branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello!"
