name: Node - Lint

on:
  push:
    branches: [ "**" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar lint
        run: npm run lint
