name: Python - Tests & Coverage

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Debug - ver archivos clave
        run: |
          pwd
          ls -la
          echo "----"
          ls -la pyproject.toml requirements.txt || true
          echo "----"
          find tests -maxdepth 2 -type f || true
          echo "----"
          find python_src -maxdepth 3 -type f || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: pytest -q

      - name: Coverage
        run: pytest --cov=oscarsavgom --cov-report=term-missing
